// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Base64Decode(arg1:string,arg2:boolean):Promise<string>;

export function Base64Encode(arg1:string,arg2:boolean):Promise<string>;

export function CheckPort(arg1:string,arg2:number):Promise<main.PortCheckResult>;

export function GeneratePasswords(arg1:main.PasswordOptions,arg2:number):Promise<Array<string>>;

export function GenerateUuids(arg1:number,arg2:number,arg3:boolean,arg4:boolean):Promise<Array<string>>;

export function HashBytes(arg1:Array<number>):Promise<main.HashResult>;

export function HashFile(arg1:string):Promise<main.HashResult>;

export function HashText(arg1:string):Promise<main.HashResult>;

export function KillPort(arg1:number):Promise<void>;

export function ListPorts():Promise<Array<main.PortEntry>>;

export function OpenDialog(arg1:string,arg2:Array<main.DialogFilter>):Promise<string>;

export function PingHost(arg1:string):Promise<boolean>;

export function QrDecode(arg1:Array<number>):Promise<string>;

export function QrEncode(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveDialog(arg1:string,arg2:string,arg3:Array<main.DialogFilter>):Promise<string>;

export function UrlDecode(arg1:string,arg2:boolean):Promise<string>;

export function UrlEncode(arg1:string,arg2:boolean):Promise<string>;

export function WriteFile(arg1:string,arg2:Array<number>):Promise<void>;
