// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Base64Decode(arg1, arg2) {
  return window['go']['main']['App']['Base64Decode'](arg1, arg2);
}

export function Base64Encode(arg1, arg2) {
  return window['go']['main']['App']['Base64Encode'](arg1, arg2);
}

export function CheckPort(arg1, arg2) {
  return window['go']['main']['App']['CheckPort'](arg1, arg2);
}

export function GeneratePasswords(arg1, arg2) {
  return window['go']['main']['App']['GeneratePasswords'](arg1, arg2);
}

export function GenerateUuids(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateUuids'](arg1, arg2, arg3, arg4);
}

export function HashBytes(arg1) {
  return window['go']['main']['App']['HashBytes'](arg1);
}

export function HashFile(arg1) {
  return window['go']['main']['App']['HashFile'](arg1);
}

export function HashText(arg1) {
  return window['go']['main']['App']['HashText'](arg1);
}

export function KillPort(arg1) {
  return window['go']['main']['App']['KillPort'](arg1);
}

export function ListPorts() {
  return window['go']['main']['App']['ListPorts']();
}

export function OpenDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenDialog'](arg1, arg2);
}

export function PingHost(arg1) {
  return window['go']['main']['App']['PingHost'](arg1);
}

export function QrDecode(arg1) {
  return window['go']['main']['App']['QrDecode'](arg1);
}

export function QrEncode(arg1) {
  return window['go']['main']['App']['QrEncode'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function SaveDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDialog'](arg1, arg2, arg3);
}

export function UrlDecode(arg1, arg2) {
  return window['go']['main']['App']['UrlDecode'](arg1, arg2);
}

export function UrlEncode(arg1, arg2) {
  return window['go']['main']['App']['UrlEncode'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
